### ISSUE TITLE
Cop idea: merge `.first` || `.create!` into `.first_or_create!`

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rails-style-guide#350]
```ruby
# bad
def method
  users.where(name: name).first ||
    users.where(name: name).create!
end

# bad
def method
  users.where(name: name).first ||
    users.create!(name: name)
end

# good
def method
  users.where(name: name).first_or_create!
end
```

And for similar methods like find_or_create_by, find_or_create_by!, find_or_initialize_by, first_or_create, first_or_create!, first_or_initialize, create_or_find_by and create_or_find_by!

**Comment by ydakuka** [comment]
The "good" style is preferable to me, because it helps me organize my code better. 

Compare with this example (from my project):

```ruby
def hsh
  { name: name }
end
```
```ruby
# before

def method1
  users.where(hsh).first || users.create!(hsh)
end

def method2
  users.where(hsh).first || users.where(hsh.merge(premium: true)).create!
end
```

```ruby
# after

def method1
  users.where(hsh).first_or_create!
end

def method2
  users.where(hsh).first || users.where(hsh.merge(premium: true)).create!
end
```

**Comment by Linuus** [comment]
Isn't `first_or_create` deprecated? https://github.com/rails/rails/pull/29584#issuecomment-311427304

**Comment by Linuus** [comment]
Maybe we should add a cop that warns when `first_or_create` is used instead 😬

**Comment by pirj** [comment]
Let’s leave it out to the Rails team to print deprecation warnings.
